spring.application.name=uravugalmatrimony

# Hibernate & JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# MySQL datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Uravugal_NewDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
# spring.datasource.username=admin
# spring.datasource.password=Krish820
spring.datasource.username=root
spring.datasource.password=root
# Server config
server.address=0.0.0.0
server.port=9100
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# AWS S3 Config
aws.access.key.id=
aws.access.key.secret=
aws.region=
aws.s3.bucket=
aws.s3.bucket.documents=
aws.s3.bucket.videos=
aws.s3.bucket.gallery=
aws.s3.bucket.sponsor=

# Razorpay Config
razorpay.key.id=
razorpay.key.secret=

# MVC config
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
